export const HAS_LAUNCHED = 'HAS_LAUNCHED'


// USER DATA
export const USER_DATA_DAILY_STEP_TARGET = 'USER_DATA_DAILY_STEP_TARGET'
export const USER_DATA_AGE = 'USER_DATA_AGE'
export const USER_DATA_HEIGHT = 'USER_DATA_HEIGHT'
export const USER_DATA_WEIGHT = 'USER_DATA_WEIGHT'
export const USER_DATA_GENDER = 'USER_DATA_GENDER'
export const USER_DATA_DAILY_ACTIVITIES = 'USER_DATA_DAILY_ACTIVITIES'
export const USER_DATA_USERNAME = 'USER_DATA_USERNAME'
export const USER_DATA_CALORIES_TMR = 'USER_DATA_TMR'
export const USER_DATA_CALORIES_BMR = 'USER_DATA_BMR'
export const USER_DAILY_FAT_GRAMS = 'USER_DAILY_FAT_GRAMS'
export const USER_DAILY_PROTEINS_GRAMS = 'USER_DAILY_PROTEINS_GRAMS'
export const USER_DAILY_CARBS_GRAMS = 'USER_DAILY_CARBS_GRAMS'


export const USER_CALORIES_JOURNAL = 'USER_CALORIES_JOURNAL'